// 素材工具插件/learning学习/12-vuex/src/App.vue
<template>
  <div id="app">
    <!-- <Bar/>
    <hr> -->
    <!-- <Foo/>
    <hr> -->
    <Goods/>
    <hr>
    <Cart/>
  </div>
</template>

<script>
// import Bar from './components/Bar'
// import Foo from './components/Foo'
import Goods from './components/Goods'
import Cart from './components/Cart'

export default {
  name: 'app',
  components: {
    // Bar,
    // Foo,
    Goods,
    Cart
  }
}
</script>

<style>

</style>

// 素材工具插件/learning学习/13-mobx/src/App.jsx
import React, { Component } from 'react';
// import Bar from './components/Bar.jsx'
// import Foo from './components/Foo.jsx'
import Goods from './components/Goods.jsx'
import Cart from './components/Cart.jsx'

import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        {/* <Bar/>
        <hr/>
        <Foo/>
        <hr/> */}
        <Goods/>
        <hr/>
        <Cart/>
      </div>
    );
  }
}

export default App;
