// 素材工具插件/learning学习/15-nuxt/components/MovieHeader.vue
<template>
  <section class="movie-header">
    <ul>
      <li>
        <nuxt-link to="/Movie/onlineTheater">正在热映</nuxt-link>
      </li>
      <li>
        <nuxt-link to="/Movie/upcoming">即将上映</nuxt-link>
      </li>
      <li>
        <nuxt-link to="/Movie/top250">top250</nuxt-link>
      </li>
    </ul>
  </section>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style lang="scss">
  .movie-header ul {
    position: fixed;
    top: 0;
    left: 0;
    display: flex;
    width: 100%;
    height: 70px;
    line-height: 70px;
    li {
      flex: 1;
      text-align: center;
      background-color: #1A2634;
      border-left: 1px solid #fff;
      a {
        display: block;
        width: 100%;
        height: 100%;
        font-size: 24px;
        color: #fff;
      }
    }
    li:first-child {
      border-left: 0 none;
    }
  }
</style>

// 素材工具插件/learning学习/16-next/components/MovieHeader.jsx
import Link from 'next/link'

export default () => (
  <section className="movie-header">
    <style jsx>{`
      .movie-header ul {
        position: fixed;
        top: 0;
        left: 0;
        display: flex;
        width: 100%;
        height: 70px;
        line-height: 70px;
      }
      .movie-header ul li {
        flex: 1;
        text-align: center;
        background-color: #1A2634;
        border-left: 1px solid #fff;
      }
      .movie-header ul li a {
        display: block;
        width: 100%;
        height: 100%;
        font-size: 24px;
        color: #fff;
      }
      .movie-header ul li:first-child {
        border-left: 0 none;
      }
    `}</style>
    <ul>
      <li>
        <Link href="/Movie?type=onlineTheater"><a>正在热映</a></Link>
      </li>
      <li>
        <Link href="/Movie?type=upcoming"><a>即将上映</a></Link>
      </li>
      <li>
        <Link href="/Movie?type=top250"><a>top250</a></Link>
      </li>
    </ul>
  </section>
)
